name = "kurogane-api"
main = "src/worker.ts"
compatibility_date = "2026-03-01"
account_id = "8e3a313e59bcc9b65726c083d17c4f2a"

[vars]
ENVIRONMENT = "production"
ANILIST_API_URL = "https://graphql.anilist.co"
FIREBASE_PROJECT_ID = "kurogane-c3c14"

[[d1_databases]]
binding = "DB"
database_name = "kurogane-d1"
database_id = "4c22119f-6d66-4199-a914-1625cf3c5dfb"

[[kv_namespaces]]
binding = "CACHE_KV"
id = "13749f55463947efaef3eaa32833b300"
